### ISSUE TITLE
Breakage in identification with Meson 1.8.0

### ISSUE THREAD

**Issue by meeq** [colcon/colcon-meson#17]
I have a colcon project that started emitting errors after updating the meson Python package to 1.8.0:

```
[0.260s] ERROR:colcon.colcon_core.package_identification:Exception in package identification extension 'meson' in 'src/scripts': InterpreterBase.__init__() missing 2 required positional arguments: 'subproject_dir' and 'env'
Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/colcon_core/package_identification/__init__.py", line 144, in _identify
    retval = extension.identify(_reused_descriptor_instance)
  File "/venv/lib/python3.10/site-packages/colcon_meson/identification.py", line 122, in identify
    parser = CustomInterpreter(desc.path, "", "")
  File "/venv/lib/python3.10/site-packages/colcon_meson/identification.py", line 26, in __init__
    super().__init__(source_root, subdir, subproject)
TypeError: InterpreterBase.__init__() missing 2 required positional arguments: 'subproject_dir' and 'env'
```

It looks like the arguments for InterpreterBase have changed from [1.7.2](https://github.com/mesonbuild/meson/blob/082917b40c8416bde925c64d22a2e60b2c059120/mesonbuild/interpreterbase/interpreterbase.py#L69-L70) to [1.8.0](https://github.com/mesonbuild/meson/blob/39be44fed2938ad03f8e2bc183401a121387bf50/mesonbuild/interpreterbase/interpreterbase.py#L71-L72):

### 1.7.2
```python
class InterpreterBase:
    def __init__(self, source_root: str, subdir: str, subproject: 'SubProject'):
```

### 1.8.0
```python
class InterpreterBase:
    def __init__(self, source_root: str, subdir: str, subproject: SubProject, subproject_dir: str, env: environment.Environment):
```

For now, I have pinned my project's `meson` Python dependency to 1.7.2

**Comment by christianrauch** [comment]
Thanks for reporting. I assume you installed colcon and the extensions via pip? If you use the Ubuntu (LTS) or RHEL packages, they will be pinned to a specific version, e.g. meson 1.3.2 for Ubuntu 24.04.

Since the meson extension is using the meson Python library directly, and meson does not have a stable Python API, these breakages are going to happen from time to time. If we get the meson version from the module, we could workaround this with a simple if/elif.

Happy to accept a PR fixing this :-) Otherwise, I will have a look at this when I have to use a newer meson version myself.

**Comment by christianrauch** [comment]
@meeq A new version has been released and can now be accessed via `pip install -U colcon-meson`.

@cottsay Can you do the DEB/RPM releases?

**Comment by bobzwik** [comment]
> [@meeq](https://github.com/meeq) Can you test if [#18](https://github.com/colcon/colcon-meson/pull/18) works for you?

I also had the same issue as @meeq which i had temporarily solved by using meson 1.7.2. Your new commit fixes the issue for me, even with meson 1.9.1. Thanks!
